stages:
  - build
  - test
  - analyse
  - package
  - deploy

variables:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"

build:
  stage: build
  tags:
    - docker
  cache:
    paths:
      - $maven_packages_cache
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expire_in: 1 week
    paths:
      - "target/*"
  script:
    - mvn compile

test:
  stage: test
  cache:
    paths:
      - $maven_packages_cache
  tags:
    - docker
  dependencies:
    - build
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expire_in: 1 week
    paths:
      - "target/surefire-reports/*"
      - "target/site/jacoco/*"
  script:
    - mvn test

analyse:
  stage: analyse
  cache:
    paths:
      - $maven_packages_cache
  tags:
    - docker
  dependencies:
    - build
    - test
  script:
    - mvn sonar:sonar -Dsonar.projectKey=game2048 -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=e7f82f027e1019a0965846db206ea04dc6717c88

package:
  stage: package
  cache:
    paths:
      - $maven_packages_cache
  tags:
    - docker
  dependencies:
    - build
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    expire_in: 1 week
    paths:
      - "target/*.war"
  script:
    - mvn package

deploy:
  stage: deploy
  tags:
    - shell
  dependencies:
    - package
  when: manual
  environment:
    name: test
    action: start
    url: http://localhost:8080/game2048
    on_stop: stop
  script:
    - docker rm --force game2048
    - docker image rm --force game2048
    - echo -e 'FROM tomcat:9-jdk17-openjdk-slim \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
    - docker run --rm -d --name game2048 -p 8080:8080 game2048

stop:
  stage: deploy
  tags:
    - shell
  when: manual
  environment:
    name: test
    action: stop
  script:
    - docker rm --force game2048
    - docker image rm --force game2048