stages:
  - build
  - test

variables:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"

build:
  stage: build
  tags:
    - docker
  cache:
    paths:
      - $maven_packages_cache
  script:
    - mvn compile

test:
  stage: test
  cache:
    paths:
      - $maven_packages_cache
  tags:
    - docker
  script:
    - mvn test